#!/usr/bin/env bash
# Hugo wrapper
set -eu -o pipefail

# MacOS lover's, I did not forget you ;)
PROJECT_ROOT="$(cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
cd "$PROJECT_ROOT"

# Check https://app.netlify.com/sites/breizhcamp-production/settings/env#HUGO_VERSION when change this:
HUGO_VERSION=0.73.0

install_hugo() {
  mkdir -p .hugo
  case "`uname`" in
  Darwin* )
    curl -L "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_macOS-64bit.tar.gz" | \
    zcat | (cd .hugo; tar -xf -)
    ;;
  Linux* )
    curl -L "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz" | \
      (cd .hugo; tar xzf -)
    ;;
  esac

  if [[ ! -x "$HUGO" ]]; then
    echo "Unable to install Hugo binary, exiting..."
    exit 1
  fi
}

case "`uname`" in
  Darwin*)
    HUGO=".hugo/hugo"
    ;;
  Linux*)
    HUGO=".hugo/hugo"
    ;;
  *)
    echo "No Unable to find Hugo binary, exiting..."
    exit 1
esac

[[ ! -x "$HUGO" ]] && install_hugo

"$HUGO" "$@"
